resources:
  repositories:
    - repository: IgniteUIDocFX
      endpoint: ESShared
      type: github
      name: IgniteUI/igniteui-docfx
      ref: '$(Build.SourceBranch)'

stages:
- stage: Build
  pool:
    name: BuildAgentOnPrem
    demands: npm
  jobs:
  - job: BuildDocs
    steps:
      - checkout: self
        path: '$(Pipeline.Workspace)\uno'
        
      - checkout: IgniteUIDocFX
        path: '$(Pipeline.Workspace)\dos'