parameters:
  - name: lang
    type: string
  - name: isVerbose
    type: boolean
    default: false
  - name: buildType
    type: string

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: custom
      workingDir: $(Build.SourcesDirectory)
      verbose: ${{ parameters.isVerbose }}
      customCommand: 'install --loglevel silly --production=false'

  - task: Npm@1
    displayName: npm build ${{ parameters.buildType }} ${{ parameters.lang }}
    inputs:
      command: custom
      workingDir: $(Build.SourcesDirectory)
      verbose: ${{ parameters.isVerbose }}
      customCommand: run build-${{ parameters.buildType }} -- --lang=${{ parameters.lang }}

  - task: ArchiveFiles@2
    displayName: 'Package ${{ parameters.buildType }} ${{ parameters.lang }} - zip'
    inputs:
      verbose: ${{ parameters.isVerbose }}
      rootFolderOrFile: $(Build.SourcesDirectory)/${{ parameters.lang }}/_site
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.buildType }}_${{ parameters.lang }}.zip
      replaceExistingArchive: true
