parameters:
  - name: lang
    type: string
  - name: isVerbose
    type: boolean
    default: false

steps:
  - task: Npm@1
    displayName: 'npm ci'
    inputs:
      command: custom
      workingDir: $(Build.SourcesDirectory)
      verbose: ${{ parameters.isVerbose }}
      customCommand: ci

  - task: Npm@1
    displayName: npm build staging ${{ parameters.lang }}
    condition: ne(variables['Build.SourceBranchName'], 'master')
    inputs:
      command: custom
      workingDir: $(Build.SourcesDirectory)
      verbose: ${{ parameters.isVerbose }}
      customCommand: run build-staging -- --lang=${{ parameters.lang }}

  - task: Npm@1
    displayName: npm build prod ${{ parameters.lang }}
    condition: eq(variables['Build.SourceBranchName'], 'master')
    inputs:
      command: custom
      workingDir: $(Build.SourcesDirectory)
      verbose: ${{ parameters.isVerbose }}
      customCommand: run build-production -- --lang=${{ parameters.lang }}
